server:
  port: 8888

spring:
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations:
          - file://${user.home}/config-data

eureka:  
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_DISCOVERY_SERVICE_HOSTNAME:localhost}:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: TRACE
